import pyautogui
from time import sleep

class limpeza:
    def iniciar (self):
#excluindo arquivos TEMP
        pyautogui.hotkey('win', 'r')
        sleep(1.5)
        pyautogui.write('temp')
        sleep(1.5)
        pyautogui.press('enter')
        sleep(1.5)
        pyautogui.hotkey('ctrl', 'a')
        pyautogui.press('delete')
        pyautogui.press('enter')
        sleep(1.5)
        pyautogui.press('esc')
        sleep(1.5)
        pyautogui.hotkey('alt', 'f4')
#agora excluindo em %TEMP%
        pyautogui.hotkey('win', 'r')
        sleep(1.5)
        pyautogui.write('%temp%')
        sleep(1.5)
        pyautogui.press('enter')
        sleep(1.5)
        pyautogui.press('tab')
        pyautogui.hotkey('ctrl', 'a')
        sleep(1.5)
        pyautogui.press('delete')
        pyautogui.press('enter')
        pyautogui.press('esc')
        pyautogui.hotkey('alt', 'f4')
        pyautogui.hotkey('alt', 'f4')
        pyautogui.press('enter')
        pyautogui.hotkey('alt', 'f4')
#Excluir historico do google sem excluir as senhas salvas...
        sleep(1.5)
        pyautogui.press('win')
        sleep(2)
        pyautogui.write('google')
        sleep(1.5)
        pyautogui.press('enter')
        sleep(1.5)
        pyautogui.press('f11')
        sleep(1.5)
        pyautogui.hotkey('ctrl', 'h')
        sleep(2)
        pyautogui.press('tab')
        pyautogui.press('down')
        pyautogui.press('down')
        sleep(1.5)
        pyautogui.press('enter')
        sleep(2)
        pyautogui.press('tab')
        sleep(2)
        pyautogui.press('enter')
        sleep(2)
        pyautogui.hotkey('alt', 'f4')
started = limpeza()
started.iniciar()
